name: build

on:
  push:
    branches:
      - main

jobs:
  build_package:
    name: Build package - Zookeeper ${{ matrix.zookeeper_version.major }}.${{ matrix.zookeeper_version.minor }}.${{ matrix.zookeeper_version.patch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        zookeeper_version:
          - { major: 3, minor: 8, patch: 0, latest: true, revision: 1 }
          - { major: 3, minor: 7, patch: 1, latest: false, revision: 1 }
          - { major: 3, minor: 6, patch: 3, latest: false, revision: 1 }

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        name: Extract docker image metadata
        uses: docker/metadata-action@v4.0.1
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
            public.ecr.aws/bitcompat/${{ github.event.repository.name }}
          tags: |
            ${{ matrix.zookeeper_version.latest && 'latest' || '' }}
            ${{ matrix.zookeeper_version.major }}.${{ matrix.zookeeper_version.minor }}.${{ matrix.zookeeper_version.patch }}-bullseye-r${{ matrix.zookeeper_version.revision }}
            ${{ matrix.zookeeper_version.major }}.${{ matrix.zookeeper_version.minor }}.${{ matrix.zookeeper_version.patch }}-bullseye
            ${{ matrix.zookeeper_version.major }}.${{ matrix.zookeeper_version.minor }}.${{ matrix.zookeeper_version.patch }}
            ${{ matrix.zookeeper_version.major }}.${{ matrix.zookeeper_version.minor }}
            type=sha
            type=sha,format=long

      - name: Build and Push container images
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            ZOOKEEPER_VERSION=${{ matrix.zookeeper_version.major }}.${{ matrix.zookeeper_version.minor }}.${{ matrix.zookeeper_version.patch }}
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha,scope=zookeeper-${{ matrix.java_version.major }}
          cache-to: type=gha,mode=max,scope=zookeeper-${{ matrix.java_version.major }}

      - name: Sign image with a key
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY ${TAGS}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
